export const advisoryBoard = [{
    id: 1,
    name: "Anas Rahman Junaid",
    designation: "Founder and MD of Hurun India",
    desc: "XMEC, Batch of 2005",
    imageUrl: require("../../Assets/team/anas.jpg"),
    linkedin: 'https://www.linkedin.com/in/anasrahmanjunaid',
},
{
    id: 2,
    name: "Jacob Pattara",
    designation: "AVP Product at PayTM",
    desc: "XMEC Batch of 2009. Started E-Cell MEC. Had a startup called WeavedIn, acquired by PayTM.",
    imageUrl: require("../../Assets/team/jacob.jpg"),
    linkedin: 'https://www.linkedin.com/in/jacobpattara',
},
{
    id: 3,
    name: "Samir Madhavan",
    designation: "Principal/Founder of Saitama Solutions",
    desc: "Author of popular book 'Mastering Python for Data Science'. E- Cell Chairman 2010. XMEC Batch of 2010",
    imageUrl: require("../../Assets/team/samir.jpg"),
    linkedin: 'https://www.linkedin.com/in/samir-madhavan-7b172115',
},
];


export const executiveMembers = [{
    id: 1,
    name: "Namith Krishnan",
    designation: "Chief Executive Officer",
    imageUrl: require("../../Assets/team/allen.jpg"),
    linkedin: 'https://www.linkedin.com/in/allen-joseph-b72221124/',

},
{
    id: 2,
    name: "Niranjana",
    designation: "Chief Operating Officer",
    imageUrl: require("../../Assets/team/niranjana.jpg"),
    linkedin: 'https://www.linkedin.com/in/ansif/',
},
{
    id: 3,
    name: "Amalraj K",
    designation: "Chief Financial Officer",
    imageUrl: require("../../Assets/team/amalraj.jpg"),
    linkedin: 'https://www.linkedin.com/in/aswin-shanil-150a55160/',
},
{
    id: 4,
    name: "Rindish Krishna",
    designation: "Chief Technology Officer",
    imageUrl: require("../../Assets/team/rindish.jpg"),
    linkedin: 'https://www.linkedin.com/in/123vivekr/',
},
{
    id: 5,
    name: "Abhiram Anil",
    designation: "Chief Design Officer",
    imageUrl: require("../../Assets/team/hari.jpg"),
    linkedin: 'https://www.linkedin.com/in/harinarayanan-shaji/',
},
{
    id: 6,
    name: "Muhammed Razeen",
    designation: "Chief Marketing Officer",
    imageUrl: require("../../Assets/team/Raz.jpg"),
    linkedin: 'https://www.linkedin.com/in/alan-sebastian-george-09172615b/',
},
{
    id: 7,
    name: "Neetha Jayan",
    designation: "Chief Social Media Officer",
    imageUrl: require("../../Assets/team/neetha.jpeg"),
    linkedin: 'https://www.linkedin.com/in/medha-lakshman-rao-8138aa186/',
},
{
    id: 8,
    name: "Aswathy S Menon",
    designation: "Chief Content Officer",
    imageUrl: require("../../Assets/team/aswathy.jpeg"),
    linkedin: 'https://www.linkedin.com/in/suvarnasivadas/',
},
{
    id: 9,
    name: "Nikita Menon",
    designation: "Chief Project Managament Officer",
    imageUrl: require("../../Assets/team/nikita.jpg"),
    linkedin: 'https://www.linkedin.com/in/ashmi-fathima/',
},
{
    id: 10,
    name: "Denil Geo Daise",
    designation: "Head of Outreach & Public Relations",
    imageUrl: require("../../Assets/team/denil.jpg"),
    linkedin: 'https://www.linkedin.com/in/medha-lakshman-rao-8138aa186/',
},
{
    id: 11,
    name: "Malavika R Vikraman",
    designation: "Head of Social Responsibilty",
    imageUrl: require("../../Assets/team/malavika.jpg"),
    linkedin: 'https://www.linkedin.com/in/suvarnasivadas/',
},
{
    id: 12,
    name: "Adithya Anilkumar",
    designation: "Chief Event Management Officer",
    imageUrl: require("../../Assets/team/adithya.jpg"),
    linkedin: 'https://www.linkedin.com/in/ashmi-fathima/',
},
{
    id: 13,
    name: "Abhiram Vijayakumar",
    designation: "Chief Community Officer",
    imageUrl: require("../../Assets/team/abhiram.jpg"),
    linkedin: 'https://www.linkedin.com/in/ashmi-fathima/',
},
{
    id: 14,
    name: "Vishnumaya S Unni",
    designation: "Talks Manager",
    imageUrl: require("../../Assets/team/vishnumayaunni.jpeg"),
    linkedin: 'https://www.linkedin.com/in/medha-lakshman-rao-8138aa186/',
},
{
    id: 15,
    name: "Sharath Jacob Jacon",
    designation: "Talks Manager",
    imageUrl: require("../../Assets/team/sharat.jpeg"),
    linkedin: 'https://www.linkedin.com/in/suvarnasivadas/',
},
{
    id: 16,
    name: "Maria Rachel Joseph",
    designation: "SIG Head",
    imageUrl: require("../../Assets/team/maria.jpeg"),
    linkedin: 'https://www.linkedin.com/in/ashmi-fathima/',
}
];

export const webTeam = [{
    id: 1,
    name: "Nikita Menon",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/nikita.jpg"),
    linkedin: 'https://www.linkedin.com/in/nikita-menon-b2248079/',
},
{
    id: 2,
    name: "Adithya Anilkumar",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/adithya.jpg"),
    linkedin: 'https://www.linkedin.com/in/adithyaanilkumar/',
},
{
    id: 3,
    name: "Aldrin Jenson",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/aldrin.jpg"),
    linkedin: 'https://www.linkedin.com/in/aldrinjenson/',
},
{
    id: 4,
    name: "Arti Bhatia",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/arti.jpg"),
    linkedin: 'https://www.linkedin.com/in/arti-bhatia/',
},
{
    id: 5,
    name: "Ameen",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/ameen.jpg"),
    linkedin: 'https://www.linkedin.com/in/ameen-azeez/',
},
{
    id: 6,
    name: "Rindish Krishna",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/rindish.jpg"),
    linkedin: 'https://www.linkedin.com/in/rindishkrishna/',
},
{
    id: 7,
    name: "Maria Rachel Joseph",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/maria.jpeg"),
    linkedin: 'https://www.linkedin.com/in/maria-rachel-joseph-4b80231a2/',
},
{
    id: 8,
    name: "Vishruth S",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/vishruth.jpg"),
    linkedin: 'www.linkedin.com/in/vishruth-subramanian/',
},
{
    id: 9,
    name: "Ashwin Girish",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/ashwin.jpeg"),
    linkedin: 'https://www.linkedin.com/in/ashwin-girish-895276157/',
},
{
    id: 10,
    name: "Khushi Shah",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/khushi.jpeg"),
    linkedin: 'https://www.linkedin.com/in/khushi-bharat-kumar-shah-7a94031aa/',
},
{
    id: 11,
    name: "Ranjana",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/ranjana.jpg"),
    linkedin: 'https://www.linkedin.com/in/ranjana-reghunath/',
},
];


export const secondYears = [
]
