export const advisoryBoard = [{
    id: 1,
    name: "Anas Rahman Junaid",
    designation: "Founder and MD of Hurun India",
    desc: "XMEC, Batch of 2005",
    imageUrl: require("../../Assets/team/anas.jpg"),
    linkedin: 'https://www.linkedin.com/in/anasrahmanjunaid',
},
{
    id: 2,
    name: "Jacob Pattara",
    designation: "AVP Product at PayTM",
    desc: "XMEC Batch of 2009. Started E-Cell MEC. Had a startup called WeavedIn, acquired by PayTM.",
    imageUrl: require("../../Assets/team/jacob.jpg"),
    linkedin: 'https://www.linkedin.com/in/jacobpattara',
},
{
    id: 3,
    name: "Samir Madhavan",
    designation: "Principal/Founder of Saitama Solutions",
    desc: "Author of popular book 'Mastering Python for Data Science'. E- Cell Chairman 2010. XMEC Batch of 2010",
    imageUrl: require("../../Assets/team/samir.jpg"),
    linkedin: 'https://www.linkedin.com/in/samir-madhavan-7b172115',
},
{
    id: 4,
    name: "Paul Thomas",
    designation: "Former Principal Software Consultant at Sequoia India",
    desc: "",
    imageUrl: require("../../Assets/team/paul_thomas.jpeg"),
    linkedin: 'https://www.linkedin.com/in/paul-thomas-b3241824/',
},
];


export const executiveMembers = [{
    id: 1,
    name: "Muhammed Razeen V",
    designation: "Chief Executive Officer",
    imageUrl: require("../../Assets/team/Raz.jpg"),
    linkedin: 'https://www.linkedin.com/in/muhammed-razeen-298815190',

},
{
    id: 2,
    name: "Adithya A",
    designation: "Chief Operating Officer",
    imageUrl: require("../../Assets/team/adithya.jpg"),
    linkedin: 'https://www.linkedin.com/in/adithyaanilkumar/',
},
{
    id: 3,
    name: "Maria Rachel Joseph ",
    designation: "Chief Financial Officer",
    imageUrl: require("../../Assets/team/maria_rachel.jpg"),
    linkedin: 'https://www.linkedin.com/in/maria-rachel-joseph-4b80231a2/',
},
{
    id: 4,
    name: "Aldrin Jenson",
    designation: "Chief Technology Officer",
    imageUrl: require("../../Assets/team/aldrin.jpg"),
    linkedin: 'https://www.linkedin.com/in/aldrinjenson/',
},
{
    id: 5,
    name: "Ashwin Girish",
    designation: "Chief Design Officer",
    imageUrl: require("../../Assets/team/ashwin_girish.jpeg"),
    linkedin: 'https://www.linkedin.com/in/abhiram-anil-55b9211a7',
},
{
    id: 6,
    name: "Sreehari Sreekumar",
    designation: "Chief Marketing Officer",
    imageUrl: require("../../Assets/team/sreehari_s.jpg"),
    linkedin: 'https://www.linkedin.com/in/sreehari-sreekumar-596597200',
},
{
    id: 7,
    name: "Gopika G ",
    designation: "Chief Social Media Officer",
    imageUrl: require("../../Assets/team/gopika_g.jpg"),
    linkedin: 'https://www.linkedin.com/in/neetha-jayan-b271161b3',
},
{
    id: 8,
    name: "Zailesh A R",
    designation: "Chief Content Officer",
    imageUrl: require("../../Assets/team/Zailesh.jpeg"),
    linkedin: 'https://www.linkedin.com/in/aswathy-s-menon',
},
{
    id: 9,
    name: "Nikita Menon",
    designation: "Chief Project Managament Officer",
    imageUrl: require("../../Assets/team/nikita.jpg"),
    linkedin: 'https://www.linkedin.com/in/nikita-menon-b2248079/',
},
{
    id: 10,
    name: "Femina P.A",
    designation: "Chief Publicity Officer",
    imageUrl: require("../../Assets/team/femina_p_a.jpg"),
    linkedin: 'https://www.linkedin.com/in/femina-p-a-87b3631a6',
},
{
    id: 11,
    name: "Reva Pradeep",
    designation: "Social Initiatives Manager",
    imageUrl: require("../../Assets/team/reva_p.JPG"),
    linkedin: 'https://www.linkedin.com/in/reva-pradeep-248546202',
},
{
    id: 12,
    name: "Ananya Daniel",
    designation: "Chief Event Management Officer",
    imageUrl: require("../../Assets/team/ananya_d.jpeg"),
    linkedin: 'https://www.linkedin.com/in/ananya-daniel-918073230/',
},
{
    id: 13,
    name: "John Tharian",
    designation: "Chief Community Officer",
    imageUrl: require("../../Assets/team/john_t.jpg"),
    linkedin: 'https://www.linkedin.com/in/johntharian',
},
{
    id: 14,
    name: "Annamma T Philip",
    designation: "Talks Manager",
    imageUrl: require("../../Assets/team/annamma_t_p.jpg"),
    linkedin: 'https://www.linkedin.com/in/vishnumayasunni',
},
{
    id: 15,
    name: "Sudeep S",
    designation: "Talks Manager",
    imageUrl: require("../../Assets/team/sudeep_s.jpeg"),
    linkedin: 'https://www.linkedin.com/in/sharat-jacob-jacob-045aa219b',
},
{
    id: 16,
    name: "Anjana Sudevan",
    designation: "SIG Head",
    imageUrl: require("../../Assets/team/anjana_s.jpg"),
    linkedin: 'https://www.linkedin.com/in/maria-rachel-joseph-4b80231a2/',
}
];

export const ex_executiveMembers_2021 = [{
    id: 1,
    name: "Allen Joseph",
    designation: "Chief Executive Officer",
    imageUrl: require("../../Assets/team/allen.jpg"),
    linkedin: 'https://www.linkedin.com/in/allen-joseph-b72221124/',
},
{
    id: 2,
    name: "Ansif T A",
    designation: "Chief Operating Officer",
    imageUrl: require("../../Assets/team/ansif.jpg"),
    linkedin: 'https://www.linkedin.com/in/ansif/',
},
{
    id: 3,
    name: "Aswin Shanil",
    designation: "Chief Financial Officer",
    imageUrl: require("../../Assets/team/aswin.jpg"),
    linkedin: 'https://www.linkedin.com/in/aswin-shanil-150a55160/',
},
{
    id: 4,
    name: "Vivek R",
    designation: "Chief Technology Officer",
    imageUrl: require("../../Assets/team/vivek.jpg"),
    linkedin: 'https://www.linkedin.com/in/123vivekr/',
},
{
    id: 5,
    name: "Harinarayanan Shaji",
    designation: "Chief Design Officer",
    imageUrl: require("../../Assets/team/hari.jpg"),
    linkedin: 'https://www.linkedin.com/in/harinarayanan-shaji/',
},
{
    id: 6,
    name: "Alan Sebastian",
    designation: "Chief Marketing Officer",
    imageUrl: require("../../Assets/team/alan.jpg"),
    linkedin: 'https://www.linkedin.com/in/alan-sebastian-george-09172615b/',
},
{
    id: 7,
    name: "Medha Lakshman Rao",
    designation: "Chief Social Media Officer",
    imageUrl: require("../../Assets/team/medha.jpg"),
    linkedin: 'https://www.linkedin.com/in/medha-lakshman-rao-8138aa186/',
},
{
    id: 8,
    name: "Suvarna Sivadas",
    designation: "Chief Content Officer",
    imageUrl: require("../../Assets/team/suvarna.jpg"),
    linkedin: 'https://www.linkedin.com/in/suvarnasivadas/',
},
{
    id: 9,
    name: "Ashmi Fathima",
    designation: "Chief Publicity Officer",
    imageUrl: require("../../Assets/team/ashmi.jpg"),
    linkedin: 'https://www.linkedin.com/in/ashmi-fathima/',
}
];

export const webTeam = [{
    id: 1,
    name: "Nikita Menon",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/nikita.jpg"),
    linkedin: 'https://www.linkedin.com/in/nikita-menon-b2248079/',
},
{
    id: 2,
    name: "Adithya Anilkumar",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/adithya.jpg"),
    linkedin: 'https://www.linkedin.com/in/adithyaanilkumar/',
},
{
    id: 3,
    name: "Aldrin Jenson",
    designation: "Webmaster",
    imageUrl: require("../../Assets/team/aldrin.jpg"),
    linkedin: 'https://www.linkedin.com/in/aldrinjenson/',
},
{
    id: 4,
    name: "Arti Bhatia",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/arti.jpg"),
    linkedin: 'https://www.linkedin.com/in/arti-bhatia/',
},
{
    id: 5,
    name: "Ameen",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/ameen.jpg"),
    linkedin: 'https://www.linkedin.com/in/ameen-azeez/',
},
{
    id: 6,
    name: "Rindish Krishna",
    designation: "Full Stack Developer",
    imageUrl: require("../../Assets/team/rindish.jpg"),
    linkedin: 'https://www.linkedin.com/in/rindishkrishna/',
},
{
    id: 7,
    name: "Maria Rachel Joseph",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/maria.jpeg"),
    linkedin: 'https://www.linkedin.com/in/maria-rachel-joseph-4b80231a2/',
},
{
    id: 8,
    name: "Vishruth S",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/vishruth.jpg"),
    linkedin: 'www.linkedin.com/in/vishruth-subramanian/',
},
{
    id: 9,
    name: "Ashwin Girish",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/ashwin.jpeg"),
    linkedin: 'https://www.linkedin.com/in/ashwin-girish-895276157/',
},
{
    id: 10,
    name: "Khushi Shah",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/khushi.jpeg"),
    linkedin: 'https://www.linkedin.com/in/khushi-bharat-kumar-shah-7a94031aa/',
},
{
    id: 11,
    name: "Ranjana",
    designation: "Front End Developer",
    imageUrl: require("../../Assets/team/ranjana.jpg"),
    linkedin: 'https://www.linkedin.com/in/ranjana-reghunath/',
},
];

