# Generated by Django 3.0.4 on 2020-04-25 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_contactform_imageservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='announcement_img'),
            preserve_default=False,
        ),
    ]
